### ISSUE TITLE
https://meetup.day/ Page not redirecting properly error in Firefox

### ISSUE THREAD

**Issue by rnwolf** [alexanderschau/meetup#1]
Hi  Looking at site in firefox v 100.0.1. on MS-Windows.

Not able to get to home page. Does work in Chrome.  Just thought you should know. 

Great site. Very useful for distributed teams.

![image](https://user-images.githubusercontent.com/117415/169573692-cd21db91-bb90-43f2-b5b8-847411bdf673.png)

**Comment by alexanderschau** [comment]
First, thanks for your positive feedback.

I already stumbled over this bug and thought it was my fault.
Thanks for reporting, I will keep an eye on it :smile:

**Comment by alexanderschau** [comment]
With the latest update this bug should be gone
